# Generated by Django 6.0.3 on 2026-04-09 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShareAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('share_unit_value', models.PositiveIntegerField(default=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_account', to='core.member')),
            ],
            options={
                'verbose_name': 'Member Share Account',
                'verbose_name_plural': 'Member Share Accounts',
            },
        ),
    ]
