# Generated by Django 6.0.3 on 2026-04-09 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membershareaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('CAPITAL', 'Capital'), ('SOCIAL', 'Social'), ('SOCIAL_PLUS', 'Social Plus')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('allow_negative', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fund Account',
                'verbose_name_plural': 'Fund Accounts',
                'ordering': ['code'],
            },
        ),
    ]
