# Generated by Django 6.0.3 on 2026-04-09 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_fund_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('late_penalty_start_date', models.DateField()),
                ('extra_penalty_start_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contribution Cycle',
                'verbose_name_plural': 'Contribution Cycles',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_cycle_year_month')],
            },
        ),
    ]
