# Generated by Django 6.0.3 on 2026-04-09 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contributioncycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberContributionObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_count_snapshot', models.PositiveIntegerField()),
                ('share_unit_value_snapshot', models.PositiveIntegerField()),
                ('capital_amount_expected', models.PositiveIntegerField()),
                ('social_amount_expected', models.PositiveIntegerField(default=2000)),
                ('social_plus_amount_expected', models.PositiveIntegerField(default=3000)),
                ('total_amount_expected', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('partially_paid', 'Partially Paid'), ('paid_unconfirmed', 'Paid (Unconfirmed)'), ('confirmed', 'Confirmed'), ('unpaid', 'Unpaid')], default='expected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='core.contributioncycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='core.member')),
            ],
            options={
                'verbose_name': 'Member Contribution Obligation',
                'verbose_name_plural': 'Member Contribution Obligations',
                'ordering': ['-contribution_cycle__year', '-contribution_cycle__month'],
                'constraints': [models.UniqueConstraint(fields=('member', 'contribution_cycle'), name='unique_obligation_member_cycle')],
            },
        ),
    ]
