# Generated by Django 6.0.3 on 2026-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_membercontributionobligation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('cycle_due_day', models.PositiveSmallIntegerField()),
                ('late_penalty_start_day', models.PositiveSmallIntegerField()),
                ('extra_penalty_start_day', models.PositiveSmallIntegerField()),
                ('social_amount', models.PositiveIntegerField(default=2000)),
                ('social_plus_amount', models.PositiveIntegerField(default=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Config',
                'verbose_name_plural': 'System Config',
            },
        ),
    ]
