# Generated by Django 6.0.3 on 2026-04-09 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending_confirmation', max_length=25)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_receipts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution Receipt',
                'verbose_name_plural': 'Contribution Receipts',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='core.membercontributionobligation')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.contributionreceipt')),
            ],
            options={
                'verbose_name': 'Contribution Receipt Item',
                'verbose_name_plural': 'Contribution Receipt Items',
                'ordering': ['receipt', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('receipt', 'obligation'), name='unique_receipt_item_receipt_obligation')],
            },
        ),
    ]
