# Generated by Django 6.0.3 on 2026-04-09 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contributionreceipt_contributionreceiptitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('penalty_type', models.CharField(choices=[('late_penalty', 'Late Penalty'), ('extra_late_penalty', 'Extra Late Penalty'), ('manual', 'Manual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('waived', models.BooleanField(default=False)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='core.membercontributionobligation')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='core.contributionreceipt')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-created_at'],
            },
        ),
    ]
