# Generated by Django 6.0.3 on 2026-04-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='extra_penalty_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='late_penalty_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
