# Generated by Django 6.0.3 on 2026-04-09 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_loanproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate_percent_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months_snapshot', models.PositiveSmallIntegerField()),
                ('total_repayment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_date', models.DateField()),
                ('first_due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.loanproduct')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
