# Generated by Django 6.0.3 on 2026-04-09 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_loanrepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('bank_charge', 'Bank Charge'), ('adjustment', 'Adjustment'), ('correction', 'Correction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('charge_date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-charge_date', '-created_at'],
            },
        ),
    ]
