# Generated by Django 6.0.3 on 2026-04-09 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_othercharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(choices=[('shares', 'Shares'), ('land', 'Land'), ('bond', 'Bond'), ('other', 'Other')], max_length=20)),
                ('investment_date', models.DateField()),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('partial_exit', 'Partial Exit')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-investment_date', '-created_at'],
            },
        ),
    ]
