# Generated by Django 6.0.3 on 2026-04-09 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfitEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profit_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_entries', to='core.investment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_profit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-profit_date', '-created_at'],
            },
        ),
    ]
