# Generated by Django 6.0.3 on 2026-04-09 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_othercharge_fund_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('contribution_capital', 'Contribution — Capital'), ('contribution_social', 'Contribution — Social'), ('contribution_social_plus', 'Contribution — Social+'), ('late_penalty', 'Late Penalty'), ('other_charge', 'Other Charge'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('investment_purchase', 'Investment Purchase'), ('investment_profit', 'Investment Profit'), ('social_expense', 'Social Expense'), ('social_plus_expense', 'Social+ Expense')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.fundaccount')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
