# Generated by Django 6.0.3 on 2026-06-13 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_membercontributionobligation_shares_to_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64, unique=True)),
                ('fixture_version', models.PositiveIntegerField()),
                ('declared_summary_date', models.DateField(blank=True, null=True)),
                ('latest_transaction_date', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='investmentprofitentry',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofitentry',
            name='is_net_coupon_income',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investmentprofitentry',
            name='withholding_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='date_precision',
            field=models.CharField(choices=[('exact', 'Exact'), ('month', 'Month'), ('period', 'Period'), ('unknown', 'Unknown')], default='exact', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='opening_interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loan',
            name='opening_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loan',
            name='opening_principal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loan',
            name='source_outstanding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='date_precision',
            field=models.CharField(choices=[('exact', 'Exact'), ('month', 'Month'), ('period', 'Period'), ('unknown', 'Unknown')], default='exact', max_length=10),
        ),
        migrations.AddField(
            model_name='othercharge',
            name='date_precision',
            field=models.CharField(choices=[('exact', 'Exact'), ('month', 'Month'), ('period', 'Period'), ('unknown', 'Unknown')], default='exact', max_length=10),
        ),
        migrations.AddField(
            model_name='socialactivityrecord',
            name='date_precision',
            field=models.CharField(choices=[('exact', 'Exact'), ('month', 'Month'), ('period', 'Period'), ('unknown', 'Unknown')], default='exact', max_length=10),
        ),
        migrations.AlterField(
            model_name='contributionreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentprofitentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_profit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('contribution_capital', 'Contribution — Capital'), ('contribution_social', 'Contribution — Social'), ('contribution_social_plus', 'Contribution — Social+'), ('late_penalty', 'Late Penalty'), ('other_charge', 'Other Charge'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('investment_purchase', 'Investment Purchase'), ('investment_profit', 'Investment Profit'), ('social_expense', 'Social Expense'), ('social_plus_expense', 'Social+ Expense'), ('share_purchase', 'Share Purchase'), ('bank_interest', 'Bank Interest'), ('joining_fee', 'Joining Fee'), ('contribution_penalty', 'Collected Contribution Penalty'), ('loan_exit_penalty', 'Collected Loan/Exit Penalty'), ('opening_balance', 'Opening Balance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='first_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_repayments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='othercharge',
            name='charge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='othercharge',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialactivityrecord',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialactivityrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_social_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankReconciliationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('calculated_cash_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stated_bank_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_total_assets', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliation', to='core.importbatch')),
            ],
            options={
                'ordering': ['-as_of_date'],
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='core.importbatch'),
        ),
        migrations.AddField(
            model_name='loan',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='core.importbatch'),
        ),
        migrations.AddField(
            model_name='othercharge',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_charges', to='core.importbatch'),
        ),
        migrations.AddField(
            model_name='socialactivityrecord',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_activity_records', to='core.importbatch'),
        ),
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income_type', models.CharField(choices=[('bank_interest', 'Bank Interest'), ('joining_fee', 'Joining Fee'), ('contribution_penalty', 'Collected Contribution Penalty'), ('loan_exit_penalty', 'Collected Loan/Exit Penalty'), ('correction', 'Correction')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('income_date', models.DateField(blank=True, null=True)),
                ('date_precision', models.CharField(choices=[('exact', 'Exact'), ('month', 'Month'), ('period', 'Period'), ('unknown', 'Unknown')], default='exact', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_entries', to='core.importbatch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_income_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-income_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContributionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('fund_type', models.CharField(choices=[('capital', 'Capital'), ('social', 'Social'), ('social_plus', 'Social Plus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_contributions', to='core.member')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_contributions', to='core.importbatch')),
            ],
            options={
                'ordering': ['year', 'month', 'member__member_number', 'fund_type'],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'member', 'year', 'month', 'fund_type'), name='unique_import_member_month_fund_contribution')],
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField()),
                ('sheet_name', models.CharField(max_length=255)),
                ('cell_reference', models.CharField(max_length=100)),
                ('source_formula', models.TextField(blank=True, default='')),
                ('source_value', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='core.importbatch')),
            ],
            options={
                'ordering': ['entity_type', 'sheet_name', 'cell_reference'],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'entity_type', 'entity_id', 'sheet_name', 'cell_reference'), name='unique_import_entity_source_reference')],
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='core.loan')),
            ],
            options={
                'ordering': ['loan', 'installment_number'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'installment_number'), name='unique_loan_installment_number')],
            },
        ),
    ]
