# Generated by Django 6.0.3 on 2026-06-13 20:29

import json
from decimal import Decimal
from pathlib import Path

from django.db import migrations, models
from django.db.models import Q, Sum


FIXTURE_PATH = Path(__file__).resolve().parents[1] / 'fixtures' / 'workbook_import_v1.json'


def reconcile_import(apps, schema_editor):
    targets = json.loads(FIXTURE_PATH.read_text(encoding='utf-8'))['targets']
    HistoricalContributionEntry = apps.get_model('core', 'HistoricalContributionEntry')
    SocialActivityRecord = apps.get_model('core', 'SocialActivityRecord')
    IncomeEntry = apps.get_model('core', 'IncomeEntry')
    OtherCharge = apps.get_model('core', 'OtherCharge')
    Loan = apps.get_model('core', 'Loan')
    LoanRepayment = apps.get_model('core', 'LoanRepayment')
    Investment = apps.get_model('core', 'Investment')
    InvestmentProfitEntry = apps.get_model('core', 'InvestmentProfitEntry')
    LedgerEntry = apps.get_model('core', 'LedgerEntry')
    MemberShareAccount = apps.get_model('core', 'MemberShareAccount')
    BankReconciliationSnapshot = apps.get_model('core', 'BankReconciliationSnapshot')

    def total(queryset, field='amount'):
        return queryset.aggregate(value=Sum(field))['value'] or Decimal('0.00')

    credits = total(LedgerEntry.objects.filter(direction='credit'))
    debits = total(LedgerEntry.objects.filter(direction='debit'))
    actual = {
        'contribution_capital': total(HistoricalContributionEntry.objects.filter(fund_type='capital')),
        'contribution_social': total(HistoricalContributionEntry.objects.filter(fund_type='social')),
        'contribution_social_plus': total(HistoricalContributionEntry.objects.filter(fund_type='social_plus')),
        'social_expenses': total(SocialActivityRecord.objects.filter(fund_account__code='SOCIAL')),
        'social_plus_expenses': total(SocialActivityRecord.objects.filter(fund_account__code='SOCIAL_PLUS')),
        'bank_interest': total(IncomeEntry.objects.filter(income_type='bank_interest')),
        'joining_fees': total(IncomeEntry.objects.filter(income_type='joining_fee')),
        'collected_penalties': total(IncomeEntry.objects.filter(income_type__in=['contribution_penalty', 'loan_exit_penalty'])),
        'bank_charges': total(OtherCharge.objects.filter(charge_type='bank_charge', direction='debit')),
        'loan_principal': total(Loan.objects.all(), 'principal_amount'),
        'loan_interest': total(Loan.objects.all(), 'total_repayment_amount') - total(Loan.objects.all(), 'principal_amount'),
        'loan_repayments': total(LoanRepayment.objects.all(), 'amount_paid'),
        'active_loan_principal': total(Loan.objects.filter(status='active'), 'principal_amount'),
        'active_loan_outstanding': total(Loan.objects.filter(status='active'), 'source_outstanding_amount'),
        'investments': total(Investment.objects.all(), 'amount_invested'),
        'investment_profits': total(InvestmentProfitEntry.objects.all()),
        'calculated_cash_balance': credits - debits,
        'expected_total_assets': BankReconciliationSnapshot.objects.get().expected_total_assets,
        'shares': total(MemberShareAccount.objects.all(), 'share_count'),
    }
    errors = {
        key: (actual[key], Decimal(str(expected)))
        for key, expected in targets.items()
        if actual[key] != Decimal(str(expected))
    }
    if errors:
        raise ValueError(f'Workbook import reconciliation failed: {errors}')

    invalid_exact_dates = (
        LedgerEntry.objects.filter(Q(date_precision='exact', entry_date__isnull=True) | Q(date_precision='unknown', entry_date__isnull=False)).count()
        + LoanRepayment.objects.filter(Q(date_precision='exact', paid_date__isnull=True) | Q(date_precision='unknown', paid_date__isnull=False)).count()
        + SocialActivityRecord.objects.filter(Q(date_precision='exact', activity_date__isnull=True) | Q(date_precision='unknown', activity_date__isnull=False)).count()
        + OtherCharge.objects.filter(Q(date_precision='exact', charge_date__isnull=True) | Q(date_precision='unknown', charge_date__isnull=False)).count()
        + IncomeEntry.objects.filter(Q(date_precision='exact', income_date__isnull=True) | Q(date_precision='unknown', income_date__isnull=False)).count()
    )
    if invalid_exact_dates:
        raise ValueError(f'Workbook import contains {invalid_exact_dates} records with fabricated or missing exact dates.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_import_normalized_workbook'),
    ]

    operations = [
        migrations.RunPython(reconcile_import, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('first_due_date__isnull', True), ('is_opening_balance', True), ('issued_date__isnull', True)), models.Q(('first_due_date__isnull', False), ('is_opening_balance', False), ('issued_date__isnull', False)), _connector='OR'), name='loan_opening_balance_dates'),
        ),
        migrations.AddConstraint(
            model_name='incomeentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_precision', 'unknown'), ('income_date__isnull', True)), models.Q(('date_precision__in', ['exact', 'month', 'period']), ('income_date__isnull', False)), _connector='OR'), name='income_date_matches_precision'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_precision', 'unknown'), ('entry_date__isnull', True)), models.Q(('date_precision__in', ['exact', 'month', 'period']), ('entry_date__isnull', False)), _connector='OR'), name='ledger_date_matches_precision'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_precision', 'unknown'), ('paid_date__isnull', True)), models.Q(('date_precision__in', ['exact', 'month', 'period']), ('paid_date__isnull', False)), _connector='OR'), name='repayment_date_matches_precision'),
        ),
        migrations.AddConstraint(
            model_name='othercharge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('charge_date__isnull', True), ('date_precision', 'unknown')), models.Q(('charge_date__isnull', False), ('date_precision__in', ['exact', 'month', 'period'])), _connector='OR'), name='other_charge_date_matches_precision'),
        ),
        migrations.AddConstraint(
            model_name='socialactivityrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity_date__isnull', True), ('date_precision', 'unknown')), models.Q(('activity_date__isnull', False), ('date_precision__in', ['exact', 'month', 'period'])), _connector='OR'), name='social_activity_date_matches_precision'),
        ),
    ]
